### ISSUE TITLE
Support DialTCP

### ISSUE THREAD

**Issue by dajohi** [samuel/go-socks#1]
Any plans on adding DialTCP support?  Would love to be able to set local bind address.

**Comment by samuel** [comment]
It's sort of possible now though not in a nice way. You can set the `Dialer` in `ProxyDialer`. 

It might make sense to add a `(*ProxyDialer) Establish(cn net.Conn) (net.Conn, error)` or some such that uses an existing connection to establish (auth) the connection. This way it's possible (i.e. easier) to allow the user of the package to setup the connection in any way they want (e.g. with TLS or TCP with local bind).
